### ISSUE TITLE
ready up time can't be deativated

### ISSUE THREAD

**Issue by rdy2go** [exskye/left-4-dead-2#1]
If i set "ready up time?" to "0" in the readyup.cfg, it doesn't deactivates the time.
Instead it is setting the ready up time to zero.

**Comment by sky-rpg** [comment]
Sorry, setting that value to 0 means that the Ready Up! period would last until everyone readies up.
If it's ending the pre-game immediately, that's a bug, and I'll have to fix it if it's still present in the latest release; Please lmk.
