### ISSUE TITLE
configs awaited in another directory; maplist config with other name

### ISSUE THREAD

**Issue by rdy2go** [exskye/left-4-dead-2#2]
The Plugin awaits the readyup.cfg and maplist.cfg in the directory "configs/readyup/"

The correct name of the maplist config is "maplists.cfg" and is in the "configs/" directory.
The "readyup.cfg" is also in the "configs/" directory.

My workaround was to move the both configs to "configs/readyup/" and rename "maplist.cfg" to "maplists.cfg"

Greetings =)

**Comment by sky-rpg** [comment]
I'm sorry to just get to these now; these issues _should_ be fixed in the latest version on the repository. If it isn't, let me know, and I can patch them in. I am in the process of writing a new version in C#,
